### ISSUE TITLE
Modules? or #include?

### ISSUE THREAD

**Issue by schungx** [jonathandturner/rhai#122]
There is an old PR https://github.com/jonathandturner/rhai/pull/55 that implements modules.

Modules shouldn't really be too hard to add, except for some plumbing that allows us to plug in a module resolver for `no-std` builds which has no file access, and defaults to a file-name based resolver.

Question: Would this help anything that can't be done with a simple `#include` directive instead?

I suppose if I'm writing really large-scale Rhai scripting, I'd appreciate modules.  But anything short of really large scale, probably isn't worth it.  If it is only to include standard headers and utility functions, then a simple file-include mechanism will do the job just fine.

Comments anybody?

**Comment by schungx** [comment]
If adding modules, it probably would be smart to just go "all-the-way", i.e. mimic the JS (and Rust) way:

```rust
import * as mod1 from "mod-1";
import { fn_a as foo, fn_b } from "mod-2";

let x = a(mod1.some_prop);    // or mod1::some_prop
let y = fn_b(x);
```

In the modules, we can have something like:

```rust
export fn fn_a(x) { ... }
export fn fn_b(x) { ... }

let x = 42;
export x;
```

**Comment by KaiserKarel** [comment]
I'm contemplating using rhai, and modules would help out for my usecase.

**Comment by schungx** [comment]
> I'm contemplating using rhai, and modules would help out for my usecase.

Can you elaborate a bit?

**Comment by KaiserKarel** [comment]
In my case; users provide scripts to interact with the system. Depending on their contract (how much they are paying), they get access to more resources. I could wrap these resources using modules; as well as that users would be able to reuse parts of their scripts.

**Comment by schungx** [comment]
You probably won't need modules for it.  This is how you might want to model this:

* One `Engine` for each user instance.  Don't worry, `Engine` is quite cheap to create.
* Expose all your functionalities as objects types and getters/setters/methods on those object types.
* Expose your objects as constants in a custom `Scope` that you pass into the `Engine`.
* Only expose/register the objects/types that the user has authority to use.
* You can even implement all your features into one single object type, but choose whether to register each getter/setter/method depending on the user.

**Comment by KaiserKarel** [comment]
Yes that is probably what I will be implementing. However some users will create medium sized scripts (probably over 2k LOCs) which are shared between teams. Providing some module system would be a nice to have feature.

**Comment by schungx** [comment]
True.  For your application, modules will be a help to code sharing.

Any preference as to syntax?

**Comment by KaiserKarel** [comment]
I'm in favor of staying as close as possible to Rust.

**Comment by schungx** [comment]
Modules probably only for scripting...  that's because the host already controls what types and functions to register with the Engine.  But I guess you'd like to organize these functions into modules also...  that might not be difficult to do, simply register the function under a path name (e.g. `"path::to::module::some_func"`).

**Comment by schungx** [comment]
Rust's modules syntax is similar to C++'s, i.e. `path::to::module`

Most scripting languages tend to use a single dot: `path.to.module`

Although using a dot makes it difficult to distinguish between an object property access or a module call:  `foo.bar` = object `foo`, property `bar` or module `foo`, item `bar` ?  It is still possible by restricting that modules always comes first, so `foo.bar` is a module access if there is a `foo` module at the root.  Using `::`, obviously, does not have this problem.

Any comments?

**Comment by xSke** [comment]
Rhai seems fitting for, say, Love2D-style game engines, where the game itself would be implemented entirely in the scripting language as a single "script" that runs the main game loop - having a module system would be very useful in this case as such a game can easily run in the tens of thousands of LoC.

**Comment by KaiserKarel** [comment]
I prefer `::` syntax for modules as it provides better disambiguation.

**Comment by schungx** [comment]
Yes, in a module (which is confined to a single script, unlike `#include` which concats script files), there will need to be some mechanism to `export` an entity within the module in order to expose it to the outside world.  We can use `pub` or `export`.

However, I'm still of the opinion that simply concatenating script files will do most of the work in a simple usage scenario instead of going to the extra complexity of adding modules.

**Comment by KaiserKarel** [comment]
`#include` should do the trick for me; but as @xSke mentions, a module system allows for larger scripts.

**Comment by schungx** [comment]
I understand the point about large scripts needing a robust module system to organize... but in such an application, almost certainly you'd care about parsing speed and execution speed.  If you're writing an entire game in Rhai, then you definitely care about speed, I suppose!

So I'd say compiling to some form of byte-code instruction set which is persistable is of a higher priority than allowing for modules.

**Comment by KaiserKarel** [comment]
I agree with that; bytecode (and async) seem more exciting features. :) Perhaps modules are better revisited when an official grammar is defined as well?

**Comment by schungx** [comment]
> an official grammar is defined as well?

Well, Rhai is small enough that an official grammar is not really going to be too interesting.  It doesn't even have first-class functions, lambdas, generics etc.  Therefore, the grammar is going to be quite straight-forward.

I toyed with the idea of using a PEG for parsing, but I can't see how it's going to add to what we already have, which is a simple (enough) top-down recursive descent parser.

**Comment by jhwgh1968** [comment]
> If someone wants to write an entire game in a scripting language, using Lua will probably be better. IMHO, Rhai seems to fit application cases where most functionalities are implemented in Rust but needs some controlling mechanism to kick-start the actions.

It's not a game, but my current project has the same structure as a game engine.

I am using Rhai as a foundation to write a custom DSL. It is simply a better base to start from and hack around with than the other common choices (Javascript, LUA, etc).

While I don't need that much performance from Rhai, I keep having the same API papercuts as a game engine dev. That's because Rust and Rhai have a mutual relationship. Rust creates a substantial API surface and a set of built-in behaviors, and Rhai is called in order to make certain decisions or perform certain actions based on that.

My current poking and hacking at Rhai is just fleshing out all of the basic types, to the point where I can write complex algorithms in it. But what I dream of is exporting entire Rust modules or types -- i.e. all of their public methods -- to Rhai automatically.

**Comment by schungx** [comment]
Probably what you need is namespacing for organizational purposes.   Modules also encapsulate behavior and data, so they are more than organizational aids.

If you want to bring Rust standard functionalities into Rhai, a suggestion is to avoid overloading the Rhai standard library (which most people will use).  I suggest you create some form of "plugin" mechanism in Rhai, some trait that allows people to automatically add "packages" to Rhai and thus automatically exposing additional functionalities.

In the end, the standard library can simply be one of those packages, and your `split_at` can be in the "string" package...

**Comment by jhwgh1968** [comment]
I can understand keeping the standard library small.

Regarding a plugin system, I have one hesitation -- and it's not about the idea.

I notice when other people try to contribute something, @schungx, you re-implement it your way rather than accepting their code. While your version is often improved, it is also slightly different.

If I work on this, then by the time I open a PR, a lot of code which won't be public yet will depend on the API looking the way it looks, and being structured the way it is.

I'm not asking for carte blanche to do as I wish. I'm asking simply this:

If I put time into developing this, will I actually be able to write it myself, get feedback, make changes, and get my commits merged once you are happy with it? Can you refrain from taking it over and just merging what you want instead?

**Comment by schungx** [comment]
Yes, I apologize.  I'll try to refrain from doing that.  It is a bad habit.  I'll try to improve on this.

A suggestion is that, since I mostly work on my own fork before merging back into this repo, it would be simpler for you to base on my fork so that we don't end up with a godzillion merge conflicts down the road...

**Comment by schungx** [comment]
And if we have a number of people interested into further developing this, maybe we need to keep in more constant communications about what each other are doing.  I'm trying out a number of _very_ large-scale architectural changes so the code base is constantly in flux, mostly in the `engine.rs` file.

**Comment by jhwgh1968** [comment]
> Yes, I apologize. I'll try to refrain from doing that. It is a bad habit. I'll try to improve on this.

To be honest, I was very close to e-mailing you about your "habit". I am quite relieved to read those words, and happy to delete that e-mail unsent.

> A suggestion is that, since I mostly work on my own fork before merging back into this repo, it would be simpler for you to base on my fork so that we don't end up with a godzillion merge conflicts down the road...

That is what I concluded. It is also why, when I opened another PR for reverse, I did it on your fork instead of upstream.

> if we have a number of people interested into further developing this, maybe we need to keep in more constant communications about what each other are doing. I'm trying out a number of very large-scale architectural changes so the code base is constantly in flux

I can understand that, and do see the benefits to the improvements you're making. I was pondering making the engine Send+Sync myself, for example.

I expect I will have to maintain my own personal fork for a while, and keeping up with your changes is just part of that. That is why I would want to merge an API "stub" or "stud", depending on your metaphor, so that it could change less frequently, or could be patched cleanly on a rebase of other code.

Right now, I will see what I can do with the current `register_*_fns` that are already defined. But I suspect I may need one more hook in the `Engine` directly, even if it is code that just calls those at the end of the day.

**Comment by schungx** [comment]
Yeah, I believe we need to start splitting the code into more portions so people will tend to tread on each other less.  And I agree it would be nice to stabilize an API surface such that more people can contribute.

I myself have to refrain from making trivial changes -- another bad habit.

**Comment by schungx** [comment]
There is an active conversation on modules here: https://github.com/schungx/rhai/issues/7

**Comment by schungx** [comment]
PR https://github.com/jonathandturner/rhai/pull/150 implements modules.
