### ISSUE TITLE
How is indexing supposed to work?

### ISSUE THREAD

**Issue by gmorenz** [jonathandturner/rhai#149]
I've been trying to understand the indexing evaluation code, and so far I'm mostly failing. The ast looks like the following

```
rhai> ["ab", "cd"][0][1]
=> 'b'

rhai> astu
[snip]
            Index(
                Array([snip]),
                Index(
                    IntegerConstant(0, (1:14),),
                    IntegerConstant(1, (1:17),),
                    (1:16),
                ),
                (1:13),
            ),
[snip]
```

with a literal interpretation of the tree being we are indexing the constant 0 with the constant 1, instead of a tree like

```
            Index(
                Index(
                    Array([snip]),
                    IntegerConstant(0, (1:14),),
                ),
                IntegerConstant(1, (1:17),),
            ),
```

I also don't believe that the evaluation rules are currently implemented as intended, since they apparently change depending on how values are created:

```
rhai> "cat"[print("b")]

"cat"[print("b")]
      ^ Indexing into an array or string expects an integer index

rhai> {"cat"}[print("b")]
b
=> [()]
```

So what is the intended evaluation order?

**Comment by gmorenz** [comment]
Expanding on my general expectations, where a, b, c, and d are arbitrary expressions I would expect

    a[b][c][d] = Ast(Index(Index(Index(a, b), c, d))

and evaluation order to go

    a_val = evaluate a
    b_val = evaluate b
    i1_val = evaluate Index(a_val, b_val)
    c_val = evaluate c
    i2_val = evaluate Index(i1_val, c)
    d_val = evaluate d
    i3_val = evaluate Index(i2_val, d)

I get the impression that this is not the order the code is intending to evaluate things in, but I do not understand why.

**Comment by schungx** [comment]
You're picking the hornet's nest!  Indexing is the most complicated part of the entire thing.

The core reason being: indexing and dotting (they are pretty much the same things) are bound to the _right_ instead of to the left.  So:

```
a[b][c][d] = Ast(Index(a, Index(b, Index(c, d)))
```

In order to evaluate this expression, you recurse into the chain, first getting index `b` of `a`, then recurse to get index `c` of the result `a[b]`, then further recurse to get the index `d` of `a[b][c]`.

Binding to the left, and your intuition goes, is easiest for _evaluation_ -- i.e. reading a value.  Binding to the right, however, is necessary if you want to _assign_ a value into the chain.

For example:

```
a[b][c][d] = x;
```

Think how you can actually update the nested array which sits all the way in `a` down the left side of the chain -- all the levels of indexing (and dotting) are merely _operators_ that act on the value of `a`.  If `a` sits at the end of a recursion chain, you're going to have problems.

Thus, indexing and dotting bind to the right.

**Comment by schungx** [comment]
> {"cat"}[print("b")]

Unfortunately, this is actually two statements:

```
{
    "cat"
}
[ print("b") ]
```

The first one is a block statement returning `"cat"`.  The second statement is an array with one element which is the result of `print("b")`, thus `[()]`.

**Comment by schungx** [comment]
> I get the impression that this is not the order the code is intending to evaluate things in, but I do not understand why.

You're correct.  That's not the order, and it is because when you're doing an assignment (i.e. updating), you need to act on the ultimate root value itself.

`eval_indexed_chain` in `engine.rs` evaluates down an indexing chain to get the values of all indexing expressions.  You can base your evaluation code on this.

Once you get a `StaticVec` of values that represent the result of each indexing expression, you can use them to index into the root variable.  Check out `eval_dot_index_chain`.

**Comment by gmorenz** [comment]
Thanks for the explanation! After that and a fair bit of playing with code it makes sense :)

For the next person who comes along, this really is the key part:

> ```
> let a = [9, 8, 7];
> a[ { a = [1, 2, 3]; 0 } ]
> ```

If we try to evaluate `a` before we evaluate any part of the index chain, then we need to hold a mutable reference to it the whole time. Since we are holding a mutable reference to a variable we can't modify it (and without a lot of work, we actually can't modify any variables).

Rust solves this problem and uses the naive evaluation order by using the borrow checker to prevent modification of `a`. Python solves this problem by using the naive evaluation order and making `a` just a pointer to an object, and not caring/dropping the object if we change what `a` refers to before we mutate it. Since we don't have a borrow checker and haven't wrapped everything in pointers, we are "stuck" being a bit more clever.

To re-iterate the proper execution order at the bottom of the issue instead of in the giant walls of text above:

in a chain a.b[c].d:

 - Evaluate the expressions except the first one (`a`) in left to right order, (`b`, `c` and then `d`)
 - Evaluate the first expression (`a`)
 - Evaluate indexing/dot operators in left to right order (`obj = a.b`, `obj = obj[c]`, and then `obj = obj.d`).

Thanks again!

**Comment by schungx** [comment]
This is a good summary.  Something to add about why this evaluation order is needed:

Indexing is not an operation on a piece of data.  It does not convert some value to another.  It _refers_ to a _portion_ of a piece of data.  In other words, it is a _referencing_ operator.  Therefore, an assignment into an indexing chain means overwriting the portion of the data as specified by the "coordinates" which are the index values.

Make sure when you evaluate a chain, you need to make sure that you don't unnecessarily copy data around.  For example:

```
a[b][c][d]
```

Means that `a` is a multi-dimensional nested array structure, and you're referring the piece of data located at coordinates `b,c,d`.  The bad thing to do is to first take `temp = a[b]`, which is actually a nested array itself.  You need to make sure you don't _copy_ this array into `temp` - which may be large.  Once you get this sub-array, you then take `temp2 = temp[c]`, yet another array, and again you don't want to copy it into `temp2`.

What you really want is to build a _reference_ based on these coordinates, and then simply offset into the root array structure and directly access/update the location.  This way you avoid most of copying.
