### ISSUE TITLE
Allow to register FnMut Functions

### ISSUE THREAD

**Issue by lammermann** [jonathandturner/rhai#151]
Hi,
in my use case I would like to register a closure in via `engine.register_fn` which executes a side effect in my surrounding environment but when I try to do this I get a compile error which says: 

> error[E0525]: expected a closure that implements the `Fn` trait, but this closure only implements `FnMut` 

Is it possible to support `FnMut` in `register_fn`? Is there a other way to archive this? Or a workaround?

Thanks very much in advance.

**Comment by schungx** [comment]
Check out `side_effects.rs` in `tests`.

You'll need to use `Rc`-wrapped interior mutable wrappers, e.g. `Rc<RefCell>`, to access anything that is mutable from a script.

The reason being that `Engine` instances can be shared and are re-entrant, so they cannot hold `FnMut`'s.

**Comment by lammermann** [comment]
Thanks for the very quick response. I try this out right now.
It seems I'm getting livetime errors. I try to call rhai inside a function and wrapping `self`. However rhai seems to expect a `static` livetime (even though the engine itself lives only in that same function). 

Is there any way I can work around this?

**Comment by schungx** [comment]
It expects `'static` because it is re-entrant, so you can technically use one instance of `Engine` in a massively-parallel way.

But because of this, you have to go through some hoops for Rhai to mutate external state - it is rather dangerous if you think about it, that a text script should be allowed to mutate state outside of the scripting engine.

I suggest that you carefully design your types to make this work seamlessly.  What you need is basically `Rc<RefCell<T>>` that allows you to keep state outside of the `Engine`, share a link to it via a variable into Rhai, and then use Rhai to call methods on that link.  Mutability is achieved through the `RefCell`.

**Comment by lammermann** [comment]
Thank you for your advice. I adjusted my types to work correctly.

Going to close this now.
