### ISSUE TITLE
clonable scope

### ISSUE THREAD

**Issue by GopherJ** [jonathandturner/rhai#153]
Hi I would like to do some multi thread testing using the cloned `Scope` which stores a basic set of data but will be mutated in other threads.

Just found Clone hasn't been implemented for Scope, can we implement Clone for it?

**Comment by schungx** [comment]
Well, you cannot clone a `Scope` because the data it holds may not be clonable.  You can basically throw in any type at all, even non-clonable ones, and Rhai will happily process it.

Maybe a clone implementation that just clones the data that is clonable and replace the non-clonable ones with `()`?

**Comment by schungx** [comment]
Yes it can be made `Clone`.  I think I was experimenting with some fields in the structures and so removed the `Clone` derive.  I can put it back in.

**Comment by schungx** [comment]
https://github.com/jonathandturner/rhai/pull/152

This now has `Scope` that is `Clone`.

**Comment by GopherJ** [comment]
@schungx thanks~
