### ISSUE TITLE
Comments Syntax

### ISSUE THREAD

**Issue by shanegibbs** [jonathandturner/rhai#17]
Would be really nice to be able to write comments in a script :)

I guess something like:

```
// some comment
```

or...

```
# another comment
```

Let me know if you need more info.

**Comment by TheMegaTB** [comment]
I was also thinking about this and in addition to 
```
// some comment
```
it would make sense to also enable
```
fn /* some comment */ add(arg1, arg2) { ... }
```

I was already thinking where one would best implement comments. The token parser seems too late for it since it already processes the code - somewhat - char by char hence some sort of preprocessor which strips comments. 
Since newlines, carriage returns and unnecessary whitespaces are considered illegal it would make sense to strip them in addition to the comments (except there is some reason that the TokenParser considers them illegal) to make for more readable code the way it is currently provided in the Readme.

Here's the location of the nl/cr/whitespace token:
https://github.com/jonathandturner/rhai/blob/master/src/parser.rs#L466

If the usage of a preprocessor is approved I could create a PR for that. Shouldn't be too hard to implement.

**Comment by luciusmagn** [comment]
Closing, added to TODO. Issue #26
