### ISSUE TITLE
How to inject values into my script

### ISSUE THREAD

**Issue by matthiasbeyer** [jonathandturner/rhai#18]
Following usecase:

I have users input rhai script. I want some environment to be set up for every invocation of the script (Lets think of a global variable that should be available when the script is run).

How do I do that?

**Comment by isavegas** [comment]
Define a scope for your runtime environment, populate it, and clone it for each individual script you want to run.

**Comment by luciusmagn** [comment]
I know I am necroing an ancient issue, but currently, the way to do would be modifying your Scope manually. Probably in the (hopefully near) future, there will be a more handy interface.

**Comment by JoshLambda** [comment]
There could be a big security issue when using Scope for this. 
Script users could read/temper with the application context through Scope while these values are only meant for internal use.

Most applications need to work with an application context, or at least some accessors to some data storage. As an example, if you use Rhai for writing macros for a wiki, then the macros have to do something to the wiki content in some way. I can't see how this could happen without passing some param/context values to Rhai's rust-side functions. This would probably happen when calling `eval` or `eval_with_scope`, like `engine.eval_with_scope(&mut scope, &mut rust_side_params_array, script);`

As it is currently, Rhai seems more like a powerful abstract programmable maths language than some scripting to embed in application, because it cannot take input from the host application itself. But with a few modifications it seems that it could be really possible though.

**Comment by schungx** [comment]
@JoshLambda  not sure I follow you.  The `Scope` is a sandboxed environment.  The script should not be able to affect anything outside of this `Scope` except through registered functions.
