### ISSUE TITLE
[Question] How do I save rhai callbacks?

### ISSUE THREAD

**Issue by TimUntersberger** [jonathandturner/rhai#217]
Hey, I am trying to register a function that takes a rhai function as parameter and saves it in a struct, so that I can later call it.
I am currently very confused and I don't know what I should do to achieve my goal. 

Should I save the AST of the function and later evaluate it?

**Setup**
```rust
engine.register_fn(
    "popup_new",
    |options: Map| {
        let mut p = Popup::new();

        for (key, val) in options {
            match key.as_str() {
                // ... other stuff
                "actions" => {
                    let actions = val.cast::<Array>();
                    
                    for action in actions {
                        let settings = action.cast::<Map>();
                        let mut action = PopupAction::default();

                        for (key, val) in settings {
                            match key.as_str() {
                                "text" => { action.text = val.to_string(); },
                                "cb" => { 
                                     // what do I do here?
                                },
                                _ => {}
                            };
                        }
                    }
                }
            };
        }
    },
)
```

**Usage**
```
popup_new(#{
    text: ["Checking for updates..."],
    padding: 5,
    actions: [#{
        text: "Update",
        cb: || { 
            print("Updating") 
        }
    }]
});
```

Thank you!

**Comment by schungx** [comment]
Well, what you want to do is to store a _function pointer_, which is a primitive type that Rhai understands.

You can then call this function pointer later on.

Rhai even has built-in shortcut to call a function pointer stored as an object map's property.

Check out the [Rhai Book](https://schungx.github.io/rhai/) for details.

**Comment by schungx** [comment]
What you want to do seems to be: you want to be able to calla  Rhai function (or closure) inside a registered Rust function.

Check out:

https://schungx.github.io/rhai/rust/register-raw.html?highlight=call,function,pointer#example---passing-a-callback-to-a-rust-function

**Comment by TimUntersberger** [comment]
Thank you!

I am now trying to save a closure that just calls the rhai function, but I am now hitting problems with the lifetime. My first thought was to just have an engine that lives for the whole program, but because the engine doesn't implement `Sync` I can't really send it between threads safely. 

I am not really sure how I should solve this.

```rust
let fp = val.cast::<FnPtr>();
let name = fp.fn_name().to_string();
action.cb = Some(Box::new(move || {
    let engine = ENGINE.lock().unwrap();
    engine.consume(&format!("Fn(\"{}\").call()", name));
}));
```

**Comment by schungx** [comment]
You can use the `sync` feature to make `Engine` `Send + Sync`.

**Comment by schungx** [comment]
> I am not really sure how I should solve this.

See the example in https://schungx.github.io/rhai/engine/func.html

It creates a Rust closure that you can store.  The closure wraps up the `Engine` and `AST`.

**Comment by TimUntersberger** [comment]
I can't really use the `sync` feature, because then the recommended way [here](https://schungx.github.io/rhai/patterns/config.html) doesn't work anymore.

```rust
let cfg = config.clone(); //Rc<RefCell<Config>>
engine.register_custom_syntax(....);
```
> See the example in https://schungx.github.io/rhai/engine/func.html

The problem is that the function is a property of a map.

**Example**
```
#{
    actions: [#{
        text: "Update",
        cb: || { 
            print("Updating") 
        }
    }]
}
```

How can I extract the function using `create_from_script` if it is contained in a map?

**Comment by schungx** [comment]
> but I don't see the `hello world` in the output. Is this expected or did I mess something else up?

Do you get an error evaluating the script?  If not, then it should have run successfully.

If you don't see the output, maybe something has eaten it?

A good way is to change some value in your shared object and then test whether the value has changed.

**Comment by TimUntersberger** [comment]
> I don't see how this can be more work than engine.consume(&ast, ...) where you'd need to dynamically generate the script in the first place.

Yeah you are right.

I probably had an error, but I didn't see it because I didn't handle the error. Everything is working now.

**Thank you**

**Comment by omrisim210** [comment]
Hello, I'd like to do a very similar thing to this:
```
#{
    actions: [#{
        text: "Update",
        cb: || { 
            print("Updating") 
        }
    }]
}
```
But I'd also like to pass variables from Rust into the Rhai callback and mutate them so the changes are visible in Rust-land. 
I've been trying various solutions (more like variations of the same idea) using `RefCell<Rc<StructIWantToMutate>>`, but I haven't managed to get anything to work.
What's an (the?) idiomatic way to achieve such a result?

Do I need to push the values I want to mutate into a scope?
If so, will the changes to the values in the scope be reflected in my Rust-owned values?
Usually I'd assume the answer is no since the values have to be cloned before being pushed into the scope, but what if the values are shared pointers?
From my understanding cloning those simply creates another reference to the value stored inside them, so in theory they should be accessible and mutable from Rhai.

Here's a small example of an attempt at solving implementing my design:
```rust
let code = r##"
#{
	name: "A",
	description: "B",
	cost: 1,
	health_added: 0,
	action: |p1, p2| { p1 += 1 }
}
"##;

let engine = Engine::new();
let mut scope = Scope::new();
let ast = engine.compile_expression_with_scope(&mut scope, code).unwrap();
let res = engine.eval_ast_with_scope::<Map>(&mut scope, &ast).unwrap();
scope.push("", res.clone());
let p1 = Rc::new(RefCell::new(0));
let p2 = Rc::new(RefCell::new(0));
let mut f = move |p1: Rc<RefCell<i32>>, p2: Rc<RefCell<i32>>| {
	let action_dyn = res.clone().get("action").unwrap().clone();
	let action_ptr = action_dyn.cast::<FnPtr>();
	let name = action_ptr.fn_name();
	engine.call_fn::<(Rc<RefCell<i32>>, Rc<RefCell<i32>>), ()>(&mut scope, &ast, name, (p1, p2));
};
println!("{},{}", *p1.borrow(), *p2.borrow()); // 0,0
let _ = f(p1.clone(), p2.clone());
println!("{},{}", *p1.borrow(), *p2.borrow()); // 0,0
```
I asume `borrow_mut` should come into play somewhere here to enable mutation of `p1` and `p2`, but `RefMut` doesn't implement `Clone` so it's impossible to pass `RefMut` arguments to a Rhai function, which in turn means Rhai can't modify the arguments passed into the function.

Sorry if it's a beginner issue, I can understand if you tell me to rtfm but I'd appreciate any help that I can get.

**Comment by omrisim210** [comment]
Sorry for bumping this again, but are you sure this is doable with a Rhai closure?

All the examples use named functions that are registered from Rust, have their logic written in it and are then used from Rhai to control the Rust program.

For my use case I don't register the functions myself so I can't have, say, `anon$cfb82eba22e3a439`, borrow its arguments mutably and operate on them.
Another issue that arises is what exactly is this operation that's performed on the borrowed arguments - I want the arguments passed into the Rhai closure to be dynamically modifiable from said closure, and no matter how hard I try to think about it I can't find a way of doing so.
Again, in the book and the test you referred to the behavior is hard-coded in Rust and only its timing and logic (when/whether to call each Rust function) is determined by the user writing Rhai, whereas I want the behavior to be dynamically determined using a Rhai closure.

I could use return values instead of mutation (I'll probably do it if what I'm trying to do right now doesn't work out) but I'd rather have my API use mutation as it's more concise for my use case.

Thanks in advance for your time.

**Comment by schungx** [comment]
To Rhai, an `Rc<RefCell<T>>` is just another data type.  It implements `Clone` and that's all Rhai cares.  To Rhai, it is no different from `i64`.

You can use it everywhere just as you use any other data type.

But if you want to mutate it inside a _script_, you'll need to register an API for your data type.  Rhai doesn't understand `borrow_mut`.  Therefore, you have to provide your own abstraction.  Methods and properties etc.

The best way to do it is to create your data type (you can type-def an `Rc<RefCell<T>>`, or you can make it `struct NewType<T>(Rc<RefCell<T>>)`.  Then you call `Engine:;register_type_with_name` to register the new type.  Then you can register your API on top of it.

Check out the Book section on custom types.

**Comment by schungx** [comment]
Let's say in your example:

```rust
    pub type MyType = Rc<RefCell<i32>;

    let code = r##"
    #{
        name: "A",
        description: "B",
        cost: 1,
        health_added: 0,
        action: |p1, p2| { p1 += p2 }
    }
    "##;

    let mut engine = Engine::new();

    engine
        .register_type_with_name::<MyType>("MyType")
        .register_get_set("data",
            |p: &mut MyType| *p.borrow(),
            |p: &mut MyType, value: i32| *p.borrow_mut() = value)
        .register_fn("+=", |p1: &mut MyType, p2: MyType| *p1.borrow_mut() += *p2.borrow())
        .register_fn("-=", |p1: &mut MyType, p2: MyType| *p1.borrow_mut() -= *p2.borrow());

    let mut scope = Scope::new();
    let ast = engine.compile_expression_with_scope(&mut scope, code)?;
    let res = engine.eval_ast_with_scope::<Map>(&mut scope, &ast)?;

    let p1 = Rc::new(RefCell::new(0));
    let p2 = Rc::new(RefCell::new(0));

    let mut f = move |p1: MyType, p2: MyType| {
        let action_ptr = res["action"].clone().cast::<FnPtr>();
        let name = action_ptr.fn_name();
        engine.call_fn::<_, ()>(&mut scope, &ast, name, (p1, p2))?;
    };
    let _ = f(p1.clone(), p2.clone());
```

I haven't checked that this works, but  you get the general idea.

**Comment by schungx** [comment]
Are you OK with this issue?  Can we close this?

**Comment by TimUntersberger** [comment]
If you are asking me, then yes I am okay with closing this. I didn't want to close this as @omrisim210 could still have some problems.

**Comment by schungx** [comment]
@omrisim210  are you OK with closing this?

**Comment by omrisim210** [comment]
I never managed to do what I wanted to do but I'm okay with closing this.

I was originally planning on having a Rust library that can read Rhai files to populate its data structures that include callbacks, but seeing as this is rather complex I ended up removing Rhai from the library.  
I'll use Rhai in an application that uses the library which I believe should make things somewhat simpler.
