### ISSUE TITLE
Issue with PartialOrd

### ISSUE THREAD

**Issue by zach-schoenberger** [jonathandturner/rhai#226]
Hello, I came across the following issue:
I was trying to use PartialOrd/PartialEq to use for comparison using the normal comparison operators. I found that custom implementation of this did not work. An example that does not work is below.

```
#[derive(Debug, Clone)]
    struct A(i64, i64);
    impl A {
        fn lt_i64(s: &mut Self, other: &i64) -> bool {
            s.0 < *other
        }
    }

    #[test]
    fn less_than_test() {
        let mut engine = Engine::default();
        engine.register_fn("<", A::lt_i64);

        let a = A(1, 5);
        let ast = engine.compile("a < 10").unwrap();
        let mut scope = Scope::new();
        scope.push("a", a);

        assert_eq!(true, engine.eval_ast_with_scope::<bool>(&mut scope, &ast).unwrap());
    }
```

If `other: &i64` is changed to `other: i64` it works. This does not even get into getting PartialOrd to work, which I believe is related to the ref/non ref shown here.

Looking for any feedback.

Thanks,
Zach

**Comment by schungx** [comment]
That's expected behavior.  All Rhai functions take owned types as parameters.

The only exception is the first parameter where it can be `&mut T`.  All others must be owned types.

Remember, if you use `&i64`, it won't match the parameter you pass into it (i.e. 10) because one is a reference and one is an integer.  Therefore the function is not found, and comparison functions default to `false`.

**Comment by zach-schoenberger** [comment]
thanks @schungx, not sure why it didn't click that the second param has to be owned.

**Comment by schungx** [comment]
> thanks @schungx, not sure why it didn't click that the second param has to be owned.

That's because it is a limitation of Rust... at least until specialization lands.

`&T` is `T` and there is no way to distinguish `T` from `&T`...
