### ISSUE TITLE
Questions.. 

### ISSUE THREAD

**Issue by Sagebati** [jonathandturner/rhai#239]
Hi, 

First of all, your work is awesome !
I was seeking for expression or DSL library, I came accross this and sounds amazing.
But I have some struggle understanding all what can I do with this lib. The book is good, but maybe open an chat (Zulip, Matrix Element) for people seeking precise help could be an idea.

I have some questions, is there any technical reason that I need to create an Engine to compile expressions ? and is the creation of an Engine expensive ?

**Comment by schungx** [comment]
Creating an Engine is not expensive.  There are some costs, but not much.  As long as you don't do it in a tight loop, you're fine.

There is also a way to _very_ cheaply create an Engine.  There is a chapter in the Book on this pattern.

Compile an expression only if you want to reuse it.  Otherwise, just use `eval` and you don't have to deal with a separate compilation step.

**Comment by schungx** [comment]
Is this issue resolved?  Anything else I can help you with?

**Comment by Sagebati** [comment]
You can close it. Thanks you.
