### ISSUE TITLE
Builtin functional ops

### ISSUE THREAD

**Issue by dmadisetti** [jonathandturner/rhai#255]
Would love `map`, `reduce`, `filter`. Looks like it would be easy to extend (function pointers are a thing yeah?), but I feel as most languages would want these as a first class function

**Comment by schungx** [comment]
Well, with closure syntax, it would almost look like first-class functions.  You can easily define these functions, but on a type-by-type basis.  That's because you cannot define a blanket function acting on, say, types that implement `Iterator` or some interface.

**Comment by schungx** [comment]
Good news.  These will be included in the next version.

Or pull from this repo later on when I land the PR.

**Comment by schungx** [comment]
The PR has landed with a whole bunch of new `Array` methods.

Please check out: https://schungx.github.io/rhai/vnext/language/arrays.html

**Comment by dmadisetti** [comment]
This looks awesome. That was super fast as well.

Thanks!

**Comment by schungx** [comment]
Well, @jhwgh1968 's work on plugins makes it super easy to add new functions.  :-)

**Comment by dmadisetti** [comment]
From the docs, just one comment

 - I think `fold` > `reduce`. This is also a little more rusty, and more general.  Reverse is typically `foldr`. Specially since the suggested api provides `()` for the initial value.

**Comment by schungx** [comment]
They reason I forced the initial value to `()` is because I don't want to register multiple versions of the same function for different initial value types.  It is extremely brittle, the current way Rhai handles it...

I thought of having a version that takes a closure that returns the initial value, and I might put that in.

Regarding the name, I struggled between `fold` and `reduce`, but then I figured since we're following a lot of ES3 here (e.g. `filter` and `map` return fresh copies of the arrays, not acting on iterators), we might make the naming more familiar, and "map-reduce" is much more familiar than "map-fold"...

ES3 has `every` instead of `all`, but it seems that `all` and `some` looks more pleasing to me than `every`/`some` (ES3) or `all`/`any` (Rust), the Rust functions both start with 'a' while `some` actually reflects back to `None`/`Some`.  I've also added a `none` function to complement.

**Comment by dmadisetti** [comment]
Ok, I think that's fair.

Just some more thoughts:

I think very specific distinction between `fold` and `reduce` that still might make this a bit of a misnomer, I know this is true for Kotlin in particular.  For `reduce` 0 elements is error, 1 element is identity, and >2 elements will work as expected (`f(..f(arr[0], arr[1]), arr[2])..., arr[n])`), where no initial value needed. Whereas `fold` operates with a given initial value. It sounds like the implicit casting of the initial value is non-trivial/ not possible so that's understandable not wanting to supply a true `fold` (the closure ok though).

The Kotlin `reduce` functionality coupled with the 'offset index' closure argument that you already provide, and users could replicate the functionality of both: you just check for `i = 0` if you want to do something fancy at the beginning.

But ultimately with a clear documentation, I don't think it super super matters?

**Comment by dmadisetti** [comment]
I know I'm already excited with the short turn around time. That was awesome. I've already got the commit in my cargo to play around with it. Thanks again

**Comment by schungx** [comment]
> I know this is true for Kotlin in particular

So, in essence, what you mean is that Kotlin attaches the initial value to the beginning of the stream?  I haven't seen many other languages doing that... most of them either just take an initial value, have a way to provide an initial value...

**Comment by dmadisetti** [comment]
Python treats reduce without an initial argument like this: https://docs.python.org/3/library/functools.html#functools.reduce
Scala makes this same distinction: https://stackoverflow.com/a/25150003
F#: https://stackoverflow.com/a/9055893

but yeah, you're right- I still think there's a bit of variability between languages, and it's really just a matter of being clear
