### ISSUE TITLE
Use ^ for power

### ISSUE THREAD

**Issue by timfish** [jonathandturner/rhai#256]
Our users are entering scientific equations and will be more used to using `^` for power.

If I call `.register_custom_operator("^", 180)` I get `"not a valid identifier: \'^\'"`. I'm guessing that this is because I can't name a function that way. Short of re-writing the string expression, is there a better way to do this?

I could write my own definition of [arithmetic.rs](https://github.com/jonathandturner/rhai/blob/edd136c04755de9766e8d36cc14494e158300898/src/packages/arithmetic.rs) and load that package instead of the default?

**Comment by schungx** [comment]
Nope.  Custom operators must all be identifiers.  You can register a custom operator called `power` etc.

However, you can simply overload the `^` operator to provide an implementation for two `FLOAT`'s.  With the only pit-fall that it is going to bind at a different precedence than the `~` operator.

I personally like `^` as a power operator, but history has it that `~` was used instead and `^` reserved for XOR... otherwise it might be necessary to remove the XOR operator, because the two precedences will conflict with each other.

**Comment by schungx** [comment]
> I could write my own definition of [arithmetic.rs](https://github.com/jonathandturner/rhai/blob/edd136c04755de9766e8d36cc14494e158300898/src/packages/arithmetic.rs) and load that package instead of the default?

Most certainly you can.  In particular, if you only support one integer type and one floating-point type, then you can remove most of the repetitive code for different integer types.

**Comment by schungx** [comment]
> Short of re-writing the string expression, is there a better way to do this?

How about a double-star operator?  `**`  Some languages use it as exponentiation, but still not `^`...
