### ISSUE TITLE
`ExprTooDeep` error on switch inside for loop

### ISSUE THREAD

**Issue by semirix** [jonathandturner/rhai#303]
I cannot run this example Rhai code:

```
10: for item in [0, 1, 2] {
11:    switch item {
12:        _ => print("Test")
13:    }
14: }
```

It produces this when run:

```
Internal("Internal Error: ErrorParsing(ExprTooDeep, 12:24)")
```

I can run the switch statement outside of the for loop but not inside it.

**Comment by schungx** [comment]
I suppose this loop is deep inside an expression?  Or multiple layers of expressions?

**Comment by schungx** [comment]
You may relax the expression nesting via `Engine::set_max_expr_depths`.

**Comment by schungx** [comment]
This is especially true when inside a function body where the nesting depth can be as small as 16 levels in debug mode.  This is for protection.

You can set your own limits or disable it altogether.

**Comment by semirix** [comment]
This is the entire file:
```
fn process() {
    
}

fn signals(signals) {
    for item in [0, 1, 2] {
        switch item {
            _ => print("Test")
        }
    }
}
```

I would hardly call that deeply nested though... Your suggestion did fix my issue though.

**Comment by schungx** [comment]
Yes, functions are deliberately set to a low nesting level... that's because you can easily nest function calls, and each function's stack depth adds up.  It is very easy to get a stack overflow just by crafting functions and then cross-call them.

The release mode has a much higher limit, and you can always relax the limit, or turn it off.

I do agree that this doesn't look very deeply-nested... but to Rhai it is: a function call is actually three-levels deep, each block is one level etc.

**Comment by schungx** [comment]
I'm open to ideas whether to relax this limit - and have novice users exposed to attacks.
