### ISSUE TITLE
More than six arguments?

### ISSUE THREAD

**Issue by Udiknedormin** [jonathandturner/rhai#51]
Having read how Rhai functions are dispatched, I don't quite get why there is a fixed number of arguments limit. Arguments are basically passed as a six-elements-long homogeneous tuple of `Option<&mut Box<Any>>` only to assume last N of them are `None`. Not only does it introduce a argument number limit but implies quite a lot of code repetition. Wouldn't it be better to use slices instead of tuples?

Of course `fn_register` needs heterogeneousity for native Rust functions, at least until variadic generics come into play. But as for now, why not introduce some macro to automate N-arguments-precisely problem? Then it would be trivial to write another macro to abstract it away just to the limit of N. And even then, any limit doesn't seem really rational for Rhai-defined functions as it doesn't depend on variadic generics (it's dynamic anyway).

**Comment by luciusmagn** [comment]
The reason is historical, I'd say. When Jonathan first wrote Rhai, he was still learning Rust. Most of the baggage this brought has been fixed by refactoring, but stuff like this still remains, as we haven't gotten to changing it yet.

It would probably be better to use slices today, yes. Addition of macros to simplify things is on the TODO list, too.

Would you be interested in developing this better dispatch for Rhai functions?

**Comment by Udiknedormin** [comment]
Surely, why not.
