### ISSUE TITLE
debug statements

### ISSUE THREAD

**Issue by luciusmagn** [jonathandturner/rhai#63]
Let's have some nice solution for tracing information from rhai when we need to debug. Current debug messeges are only a temporary solution

**Comment by stevedonovan** [comment]
This turns out to be straightforward, if `rhai::Any` inherits from `Debug` as well as `std::any::Any`. 

Then this function definition is sufficient for a quick & dirty debug dump of any arguments:

```
    use rhai::{EvalAltResult,Any};

    fn debug(args: Vec<&mut Any>) -> Result<Box<Any>, EvalAltResult> {
        println!("{:?}", args);
        Ok(Box::new(args.len()))
    }

    engine.register_fn_raw("debug".into(), None, Box::new(debug));
```
However, this _does_ mean that any user type must implement `Debug` as well as `Clone`, so some applications might need updating.  

Feels like a small price for such convenience.  Any thoughts?

**Comment by schungx** [comment]
https://github.com/jonathandturner/rhai/pull/97 supports `debug` function.

A later PR will add a `dump_ast` function that prints out the AST of an expression.
