### ISSUE TITLE
Associativity for Dot Operator

### ISSUE THREAD

**Issue by stevedonovan** [jonathandturner/rhai#64]
First, I must say - excellent project!.  But I'm puzzled by this comment in `parser.rs`

```rust
            } else if curr_prec >= 100 {
                // Always bind right to left for precedence over 100
                rhs = try!(parse_binop(input, curr_prec, rhs));
            }
```
The only such operator is Dot, and Dot associativity must be left to right `(a.b).c`, not `a.(b.c)`
If this is resolved, then I suspect that the engine can be simplified, since there are several special-cases for the dot operator.

**Comment by schungx** [comment]
The dot operator is special because we need to handle setters in addition to getters.  It is much harder to propagate changes back to a property setter recursively when binding to the left.

If binding to the left, when you propagate a value back, you need to get the output of the next-level-up property, and it is impossible to do so without recursively calling getters down the chain.  Eventually what you've done is O(n2) calls, where n = number of dot levels.

Alternatively, you can also recurse down the LHS just once and then build a list of all the return values at each level, then do your change propagation.  This is what I plan to do to support arbitrary levels of indexing in a dot-setter chain (currently only one index level supported and is hard-coded).
